
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;

import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Langgeng
 */
public class PenyewaanAlatPendakianAdmin extends javax.swing.JFrame {

    /**
     * Creates new form PenyewaanAlatPendakianAdmin
     */
    public PenyewaanAlatPendakianAdmin() {
        initComponents();
        
        getData();
        dataBaru = true;
        setLocationRelativeTo(this);
        
        setTableHeader(tabelDataPegawai);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        usernameHome.setText(username);
    }
    
    public boolean dataBaru;
    public static String username;
    private void getData(){
        try{
            java.sql.Connection conn = (java.sql.Connection)koneksi.Koneksi.koneksiDatabase();
            java.sql.Statement stmt = conn.createStatement();
            java.sql.ResultSet sql = stmt.executeQuery("SELECT "
                    + "`nip` AS `NIP`,"
                    + "`username` AS `Username`, "
                    + "`password` AS `Password`, "
                    + "`nm_lkp` AS `Nama Lengkap`, "
                    + "`alamat` AS `Alamat`, "
                    + "`no_telp` AS `No Telp`, "
                    + "`jk` AS `Jenis Kelamin`, "
                    + "`tgl_lahir` AS `Tanggal Lahir`, "
                    + "`level` AS `Level` "
                    + "FROM pegawai;");
            tabelDataPegawai.setModel(DbUtils.resultSetToTableModel(sql));
        }catch(Exception e){
            
        }
    }
    
    void setTabColor(JPanel panel, JPanel indikator, JLabel nama_tab) {
        panel.setBackground(new Color(235,152,152));
        indikator.setBackground(new Color(78,23,23));
        nama_tab.setForeground(new Color(78,23,23));
    }
    
    void resetTabColor(JPanel panel, JPanel indikator, JLabel nama_tab) {
        panel.setBackground(new Color(200,79,79));
        indikator.setBackground(new Color(200,79,79));
        nama_tab.setForeground(new Color(240,240,240));
    }
    
    void setTableHeader(JTable tabel) {
        tabel.getTableHeader().setFont(new Font("Seqoe UI", Font.BOLD, 18));
        tabel.getTableHeader().setBackground(new Color(235,152,152));
        tabel.getTableHeader().setForeground(new Color(78,23,23));
        tabel.getTableHeader().setOpaque(false);
    }
    
    private void resetFormPeg(){
        inputNIP.setText("");
        inputUsername.setText("");
        inputPassword.setText("");
        nmLengkapPeg.setText("");
        alamatPeg.setText("");
        noTelpPeg.setText("");
        btnGroupJK.clearSelection();
        inputTglLahirPeg.setCalendar(null);
        inputLevel.setText("");
        dataBaru = true;
    }
    
    private void cekJK(){
        rBtnLaki.setActionCommand("L");
        rBtnPerempuan.setActionCommand("P");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupJK = new javax.swing.ButtonGroup();
        side_bar = new javax.swing.JPanel();
        tabBeranda = new javax.swing.JPanel();
        labelTabBeranda = new javax.swing.JLabel();
        indikatorBeranda = new javax.swing.JPanel();
        tabPegawai = new javax.swing.JPanel();
        labelTabPegawai = new javax.swing.JLabel();
        indikatorTabPegawai = new javax.swing.JPanel();
        tabLogout = new javax.swing.JPanel();
        labelTabLogout = new javax.swing.JLabel();
        indikatorTabLogout = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        main_content = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        beranda = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        usernameHome = new javax.swing.JLabel();
        dataPegawai = new javax.swing.JPanel();
        form_data_kembali1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        inputNIP = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        alamatPeg = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        noTelpPeg = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        inputLevel = new javax.swing.JTextField();
        inputUsername = new javax.swing.JTextField();
        inputPassword = new javax.swing.JPasswordField();
        nmLengkapPeg = new javax.swing.JTextField();
        inputTglLahirPeg = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        rBtnLaki = new javax.swing.JRadioButton();
        rBtnPerempuan = new javax.swing.JRadioButton();
        btnResetPeg = new javax.swing.JButton();
        btnInsertPeg = new javax.swing.JButton();
        btnUpdatePeg = new javax.swing.JButton();
        btnDeletePeg = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelDataPegawai = new javax.swing.JTable();
        inputCari = new javax.swing.JTextField();
        btnCariPeg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        side_bar.setBackground(new java.awt.Color(200, 79, 79));
        side_bar.setPreferredSize(new java.awt.Dimension(300, 1080));

        tabBeranda.setBackground(new java.awt.Color(235, 152, 152));
        tabBeranda.setPreferredSize(new java.awt.Dimension(280, 60));
        tabBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabBerandaMouseClicked(evt);
            }
        });
        tabBeranda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTabBeranda.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelTabBeranda.setForeground(new java.awt.Color(78, 23, 23));
        labelTabBeranda.setText("Beranda");
        tabBeranda.add(labelTabBeranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 14, -1, -1));

        indikatorBeranda.setBackground(new java.awt.Color(78, 23, 23));
        indikatorBeranda.setPreferredSize(new java.awt.Dimension(15, 60));

        javax.swing.GroupLayout indikatorBerandaLayout = new javax.swing.GroupLayout(indikatorBeranda);
        indikatorBeranda.setLayout(indikatorBerandaLayout);
        indikatorBerandaLayout.setHorizontalGroup(
            indikatorBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        indikatorBerandaLayout.setVerticalGroup(
            indikatorBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        tabBeranda.add(indikatorBeranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        tabPegawai.setBackground(new java.awt.Color(200, 79, 79));
        tabPegawai.setPreferredSize(new java.awt.Dimension(280, 60));
        tabPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPegawaiMouseClicked(evt);
            }
        });
        tabPegawai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTabPegawai.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelTabPegawai.setForeground(new java.awt.Color(247, 231, 231));
        labelTabPegawai.setText("Data Pegawai");
        tabPegawai.add(labelTabPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 14, -1, -1));

        indikatorTabPegawai.setBackground(new java.awt.Color(200, 79, 79));
        indikatorTabPegawai.setPreferredSize(new java.awt.Dimension(15, 60));

        javax.swing.GroupLayout indikatorTabPegawaiLayout = new javax.swing.GroupLayout(indikatorTabPegawai);
        indikatorTabPegawai.setLayout(indikatorTabPegawaiLayout);
        indikatorTabPegawaiLayout.setHorizontalGroup(
            indikatorTabPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        indikatorTabPegawaiLayout.setVerticalGroup(
            indikatorTabPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        tabPegawai.add(indikatorTabPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        tabLogout.setBackground(new java.awt.Color(200, 79, 79));
        tabLogout.setPreferredSize(new java.awt.Dimension(250, 60));
        tabLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabLogoutMouseClicked(evt);
            }
        });
        tabLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTabLogout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelTabLogout.setForeground(new java.awt.Color(247, 231, 231));
        labelTabLogout.setText("Logout");
        tabLogout.add(labelTabLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 14, -1, -1));

        indikatorTabLogout.setBackground(new java.awt.Color(200, 79, 79));
        indikatorTabLogout.setPreferredSize(new java.awt.Dimension(15, 60));

        javax.swing.GroupLayout indikatorTabLogoutLayout = new javax.swing.GroupLayout(indikatorTabLogout);
        indikatorTabLogout.setLayout(indikatorTabLogoutLayout);
        indikatorTabLogoutLayout.setHorizontalGroup(
            indikatorTabLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        indikatorTabLogoutLayout.setVerticalGroup(
            indikatorTabLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        tabLogout.add(indikatorTabLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1635909092146 size150.png"))); // NOI18N

        javax.swing.GroupLayout side_barLayout = new javax.swing.GroupLayout(side_bar);
        side_bar.setLayout(side_barLayout);
        side_barLayout.setHorizontalGroup(
            side_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabPegawai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(side_barLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel3)
                .addGap(75, 75, 75))
        );
        side_barLayout.setVerticalGroup(
            side_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_barLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(tabBeranda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tabPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        getContentPane().add(side_bar, java.awt.BorderLayout.WEST);

        main_content.setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setPreferredSize(new java.awt.Dimension(1620, 100));
        Header.setLayout(new javax.swing.BoxLayout(Header, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(2246, 20));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1620, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        Header.add(jPanel4);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("RENTAL OUTDOOR");
        jLabel5.setAlignmentX(0.5F);
        Header.add(jLabel5);

        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(2246, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1620, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        Header.add(jPanel5);

        main_content.add(Header, java.awt.BorderLayout.PAGE_START);

        jScrollPane3.setBorder(null);
        jScrollPane3.setPreferredSize(new java.awt.Dimension(1620, 100));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(new java.awt.CardLayout());

        beranda.setBackground(new java.awt.Color(255, 255, 255));
        beranda.setPreferredSize(new java.awt.Dimension(1620, 980));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel22.setText("Selamat datang, ");

        usernameHome.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        usernameHome.setText("Username");

        javax.swing.GroupLayout berandaLayout = new javax.swing.GroupLayout(beranda);
        beranda.setLayout(berandaLayout);
        berandaLayout.setHorizontalGroup(
            berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(berandaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameHome)
                .addContainerGap(1192, Short.MAX_VALUE))
        );
        berandaLayout.setVerticalGroup(
            berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(berandaLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(usernameHome))
                .addContainerGap(871, Short.MAX_VALUE))
        );

        main.add(beranda, "beranda");

        dataPegawai.setBackground(new java.awt.Color(255, 255, 255));
        dataPegawai.setPreferredSize(new java.awt.Dimension(1620, 980));

        form_data_kembali1.setOpaque(false);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel21.setText("NIP");

        inputNIP.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel31.setText("Alamat");

        alamatPeg.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel32.setText("Jenis Kelamin");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel33.setText("Username");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel34.setText("Password");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel36.setText("Nama Lengkap");

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel37.setText("Tanggal Lahir ");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel38.setText("No. Telp");

        noTelpPeg.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel40.setText("Level");

        inputLevel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        inputUsername.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        inputPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        nmLengkapPeg.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        inputTglLahirPeg.setDateFormatString("yyyy-MM-dd");
        inputTglLahirPeg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputTglLahirPeg.setPreferredSize(new java.awt.Dimension(119, 33));

        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 33));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        btnGroupJK.add(rBtnLaki);
        rBtnLaki.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rBtnLaki.setText("Laki-laki");
        rBtnLaki.setOpaque(false);

        btnGroupJK.add(rBtnPerempuan);
        rBtnPerempuan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rBtnPerempuan.setText("Perempuan");
        rBtnPerempuan.setOpaque(false);

        btnResetPeg.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnResetPeg.setText("Reset");
        btnResetPeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPegActionPerformed(evt);
            }
        });

        btnInsertPeg.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnInsertPeg.setText("Insert");
        btnInsertPeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertPegActionPerformed(evt);
            }
        });

        btnUpdatePeg.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnUpdatePeg.setText("Update");
        btnUpdatePeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePegActionPerformed(evt);
            }
        });

        btnDeletePeg.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnDeletePeg.setText("Delete");
        btnDeletePeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout form_data_kembali1Layout = new javax.swing.GroupLayout(form_data_kembali1);
        form_data_kembali1.setLayout(form_data_kembali1Layout);
        form_data_kembali1Layout.setHorizontalGroup(
            form_data_kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_data_kembali1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(form_data_kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(form_data_kembali1Layout.createSequentialGroup()
                        .addComponent(btnResetPeg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInsertPeg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdatePeg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletePeg))
                    .addGroup(form_data_kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(form_data_kembali1Layout.createSequentialGroup()
                            .addComponent(jLabel38)
                            .addGap(75, 75, 75)
                            .addComponent(noTelpPeg, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(form_data_kembali1Layout.createSequentialGroup()
                            .addGroup(form_data_kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel31)
                                .addComponent(jLabel21)
                                .addComponent(jLabel33)
                                .addComponent(jLabel34)
                                .addComponent(jLabel36))
                            .addGroup(form_data_kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(alamatPeg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(form_data_kembali1Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(form_data_kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(inputNIP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inputUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inputPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nmLengkapPeg, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(form_data_kembali1Layout.createSequentialGroup()
                        .addGroup(form_data_kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel37)
                            .addComponent(jLabel40))
                        .addGap(22, 22, 22)
                        .addGroup(form_data_kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputLevel)
                            .addComponent(inputTglLahirPeg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(form_data_kembali1Layout.createSequentialGroup()
                                .addComponent(rBtnLaki)
                                .addGap(18, 18, 18)
                                .addComponent(rBtnPerempuan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        form_data_kembali1Layout.setVerticalGroup(
            form_data_kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_data_kembali1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(form_data_kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(inputNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(15, 15, 15)
                .addGroup(form_data_kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(form_data_kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(form_data_kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(nmLengkapPeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_data_kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamatPeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_data_kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noTelpPeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_data_kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(form_data_kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32)
                        .addComponent(rBtnPerempuan)
                        .addComponent(rBtnLaki))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(form_data_kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(inputTglLahirPeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(form_data_kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(inputLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(form_data_kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertPeg)
                    .addComponent(btnUpdatePeg)
                    .addComponent(btnDeletePeg)
                    .addComponent(btnResetPeg))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel39.setText("Kelola Data Pegawai");

        tabelDataPegawai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tabelDataPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIP", "Username", "Password", "Nama lengkap", "Alamat", "No Telp", "Jenis Kelamin", "Tanggal Lahir", "Level"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelDataPegawai.setRowHeight(30);
        tabelDataPegawai.setSelectionBackground(new java.awt.Color(174, 203, 248));
        tabelDataPegawai.getTableHeader().setReorderingAllowed(false);
        tabelDataPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataPegawaiMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tabelDataPegawai);

        inputCari.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        btnCariPeg.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnCariPeg.setText("Cari");
        btnCariPeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariPegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataPegawaiLayout = new javax.swing.GroupLayout(dataPegawai);
        dataPegawai.setLayout(dataPegawaiLayout);
        dataPegawaiLayout.setHorizontalGroup(
            dataPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPegawaiLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(dataPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addGroup(dataPegawaiLayout.createSequentialGroup()
                        .addComponent(form_data_kembali1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(dataPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dataPegawaiLayout.createSequentialGroup()
                                .addComponent(inputCari, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCariPeg)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dataPegawaiLayout.setVerticalGroup(
            dataPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPegawaiLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel39)
                .addGroup(dataPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataPegawaiLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(dataPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCariPeg))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dataPegawaiLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(form_data_kembali1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        main.add(dataPegawai, "data_pegawai");

        jPanel2.add(main, java.awt.BorderLayout.CENTER);

        jScrollPane3.setViewportView(jPanel2);

        main_content.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        getContentPane().add(main_content, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabBerandaMouseClicked
        CardLayout card = (CardLayout)main.getLayout();
        card.show(main, "beranda");

        setTabColor(tabBeranda, indikatorBeranda, labelTabBeranda);
        resetTabColor(tabLogout, indikatorTabLogout, labelTabLogout);
        resetTabColor(tabPegawai, indikatorTabPegawai, labelTabPegawai);
    }//GEN-LAST:event_tabBerandaMouseClicked

    private void tabPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPegawaiMouseClicked
        CardLayout card = (CardLayout)main.getLayout();
        card.show(main, "data_pegawai");

        setTabColor(tabPegawai, indikatorTabPegawai, labelTabPegawai);
        resetTabColor(tabBeranda, indikatorBeranda, labelTabBeranda);
        resetTabColor(tabLogout, indikatorTabLogout, labelTabLogout);
    }//GEN-LAST:event_tabPegawaiMouseClicked

    private void tabLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabLogoutMouseClicked
        setTabColor(tabLogout, indikatorTabLogout, labelTabLogout);
        resetTabColor(tabBeranda, indikatorBeranda, labelTabBeranda);
        resetTabColor(tabPegawai, indikatorTabPegawai, labelTabPegawai);
        
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_tabLogoutMouseClicked

    private void btnResetPegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPegActionPerformed
        resetFormPeg();
    }//GEN-LAST:event_btnResetPegActionPerformed

    private void btnUpdatePegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePegActionPerformed
        dataBaru = false;
        //cek jk
        cekJK();
        //utk tanggal
        SimpleDateFormat formatTgl = new SimpleDateFormat("yyyy-MM-dd");
        String tglLahirPeg = String.valueOf(formatTgl   .format(inputTglLahirPeg.getDate()));

        try{
            String sql = "UPDATE pegawai SET "
                    + "nip='"+inputNIP.getText()+"'"
                    + ", username='"+inputUsername.getText()+"'"
                    + ", password='"+inputPassword.getText()+"'"
                    + ", nm_lkp='"+nmLengkapPeg.getText()+"'"
                    + ", alamat='"+alamatPeg.getText()+"'"
                    + ", no_telp='"+noTelpPeg.getText()+"'"
                    + ", jk='"+btnGroupJK.getSelection().getActionCommand()+"'"
                    + ", tgl_lahir='"+tglLahirPeg+"'"
                    + ", level='"+inputLevel.getText()+"'"
                    + " WHERE nip='"+inputNIP.getText()+"';";
            
            java.sql.Connection conn = (java.sql.Connection)koneksi.Koneksi.koneksiDatabase();
            java.sql.PreparedStatement pStmt = conn.prepareStatement(sql);
            pStmt.execute();
            inputNIP.requestFocus();
            JOptionPane.showMessageDialog(null, "Perubahan data berhasil");
        }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, e);
        }
        getData();
        resetFormPeg();
        
    }//GEN-LAST:event_btnUpdatePegActionPerformed

    private void btnDeletePegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePegActionPerformed
        try{
            String nip = inputNIP.getText();
            String sql = "DELETE FROM pegawai WHERE nip='"+nip+"'";
            java.sql.Connection conn = (java.sql.Connection)koneksi.Koneksi.koneksiDatabase();
            java.sql.PreparedStatement pStmt = conn.prepareStatement(sql);
            pStmt.execute();
            JOptionPane.showMessageDialog(null, "Data akan dihapus?");
            dataBaru=true;
            resetFormPeg(); 
        }catch(SQLException | HeadlessException e){
            
        }
        getData();
    }//GEN-LAST:event_btnDeletePegActionPerformed

    private void btnInsertPegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertPegActionPerformed
        if(dataBaru == true){
            //cek jk
            cekJK();
            //utk tanggal
            SimpleDateFormat formatTgl = new SimpleDateFormat("yyyy-MM-dd");
            String tglLahirPeg = String.valueOf(formatTgl.format(inputTglLahirPeg.getDate()));
            
            try{
                String sql = "INSERT INTO pegawai VALUES ("
                        + "'"+inputNIP.getText()+"'"
                        + ",'"+inputUsername.getText()+"'"
                        + ",'"+inputPassword.getText()+"'"
                        + ",'"+nmLengkapPeg.getText()+"'"
                        + ",'"+alamatPeg.getText()+"'"
                        + ",'"+noTelpPeg.getText()+"'"
                        + ",'"+btnGroupJK.getSelection().getActionCommand()+"'"
                        + ",'"+tglLahirPeg+"'"
                        + ",'"+inputLevel.getText()+"'"
                        + ");";
                java.sql.Connection conn = (java.sql.Connection)koneksi.Koneksi.koneksiDatabase();
                java.sql.PreparedStatement pStmt = conn.prepareStatement(sql);
                pStmt.execute();
                inputNIP.requestFocus();
                JOptionPane.showMessageDialog(null, "Data berhasil dimasukkan");
            }catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, e);
            }
            getData();
            resetFormPeg();
        }
    }//GEN-LAST:event_btnInsertPegActionPerformed

    private void tabelDataPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataPegawaiMouseClicked
        dataBaru = false;        
        try{
            int row = tabelDataPegawai.getSelectedRow();
            String tabelKlik = (tabelDataPegawai.getValueAt(row, 0)).toString();
            java.sql.Connection conn = (java.sql.Connection)koneksi.Koneksi.koneksiDatabase();
            java.sql.Statement stmt = conn.createStatement();
            java.sql.ResultSet sql = stmt.executeQuery("SELECT * FROM pegawai WHERE nip='"+tabelKlik+"';");
            
            if(sql.next()){
                String nip = sql.getString("nip");
                String username = sql.getString("username");
                String password = sql.getString("password");
                String nmLkp = sql.getString("nm_lkp");
                String alamat = sql.getString("alamat");
                String noTelp = sql.getString("no_telp");
                String jk = sql.getString("jk");
                Date tglLahir = sql.getDate("tgl_lahir");
                String level = sql.getString("level");
                
                inputNIP.setText(nip);
                inputUsername.setText(username);
                inputPassword.setText(password);
                nmLengkapPeg.setText(nmLkp);
                alamatPeg.setText(alamat);
                noTelpPeg.setText(noTelp);
                if(jk.equals("L")){
                    rBtnLaki.setSelected(true);
                }else {
                    rBtnPerempuan.setSelected(true);                    
                }
                inputTglLahirPeg.setDate(tglLahir);
                inputLevel.setText(level);
            }
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_tabelDataPegawaiMouseClicked

    private void btnCariPegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariPegActionPerformed
        try{
            String keyword = inputCari.getText();

            java.sql.Connection conn = (java.sql.Connection)koneksi.Koneksi.koneksiDatabase();
            java.sql.Statement stmt = conn.createStatement();
            java.sql.ResultSet sql = stmt.executeQuery("SELECT "
                    + "`nip` AS `NIP`,"
                    + "`username` AS `Username`, "
                    + "`password` AS `Password`, "
                    + "`nm_lkp` AS `Nama Lengkap`, "
                    + "`alamat` AS `Alamat`, "
                    + "`no_telp` AS `No Telp`, "
                    + "`jk` AS `Jenis Kelamin`, "
                    + "`tgl_lahir` AS `Tanggal Lahir`, "
                    + "`level` AS `Level` "
                    + " FROM pegawai WHERE "
                    + "nip LIKE '%"+keyword+"%'"
                    + "OR username LIKE '%"+keyword+"%'"
                    + "OR password LIKE '%"+keyword+"%'"
                    + "OR nm_lkp LIKE '%"+keyword+"%'"
                    + "OR alamat LIKE '%"+keyword+"%'"
                    + "OR no_telp LIKE '%"+keyword+"%'"
                    + "OR jk LIKE '%"+keyword+"%'"
                    + "OR tgl_lahir LIKE '%"+keyword+"%'"
                    + "OR level LIKE '%"+keyword+"%';");

            tabelDataPegawai.setModel(DbUtils.resultSetToTableModel(sql));
        }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnCariPegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenyewaanAlatPendakianAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenyewaanAlatPendakianAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenyewaanAlatPendakianAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenyewaanAlatPendakianAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>    

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenyewaanAlatPendakianAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JTextField alamatPeg;
    private javax.swing.JPanel beranda;
    private javax.swing.JButton btnCariPeg;
    private javax.swing.JButton btnDeletePeg;
    private javax.swing.ButtonGroup btnGroupJK;
    private javax.swing.JButton btnInsertPeg;
    private javax.swing.JButton btnResetPeg;
    private javax.swing.JButton btnUpdatePeg;
    private javax.swing.JPanel dataPegawai;
    private javax.swing.JPanel form_data_kembali1;
    private javax.swing.JPanel indikatorBeranda;
    private javax.swing.JPanel indikatorTabLogout;
    private javax.swing.JPanel indikatorTabPegawai;
    private javax.swing.JTextField inputCari;
    private javax.swing.JTextField inputLevel;
    private javax.swing.JTextField inputNIP;
    private javax.swing.JPasswordField inputPassword;
    private com.toedter.calendar.JDateChooser inputTglLahirPeg;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel labelTabBeranda;
    private javax.swing.JLabel labelTabLogout;
    private javax.swing.JLabel labelTabPegawai;
    private javax.swing.JPanel main;
    private javax.swing.JPanel main_content;
    private javax.swing.JTextField nmLengkapPeg;
    private javax.swing.JTextField noTelpPeg;
    private javax.swing.JRadioButton rBtnLaki;
    private javax.swing.JRadioButton rBtnPerempuan;
    private javax.swing.JPanel side_bar;
    private javax.swing.JPanel tabBeranda;
    private javax.swing.JPanel tabLogout;
    private javax.swing.JPanel tabPegawai;
    private javax.swing.JTable tabelDataPegawai;
    private javax.swing.JLabel usernameHome;
    // End of variables declaration//GEN-END:variables
}
